refactor(workflows): Set Up CI CD pipeline

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -6,10 +6,6 @@ on:
   pull_request:
     branches: [ "main" ]
 
-env:
-  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
-
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
@@ -18,7 +14,20 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Login to Docker Hub
+    - name: Check Docker Hub Credentials
+      run: |
+        if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
+          echo "Error: DOCKER_HUB_USERNAME is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
+          echo "Error: DOCKER_HUB_TOKEN is not set"
+          exit 1
+        fi
+        echo "Docker Hub username is set"
+        echo "Docker Hub token is set"
+
+    - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
@@ -27,20 +36,26 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
 
-    - name: Build and push Backend
+    - name: Build Backend
       uses: docker/build-push-action@v4
       with:
         context: ./backend
         push: true
-        tags: |
-          ${{ secrets.DOCKER_HUB_USERNAME }}/taski-backend:latest
-          ${{ secrets.DOCKER_HUB_USERNAME }}/taski-backend:${{ github.sha }}
+        load: true
+        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taski-backend:latest
 
-    - name: Build and push Frontend
+    - name: Push Backend
+      run: |
+        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/taski-backend:latest
+
+    - name: Build Frontend
       uses: docker/build-push-action@v4
       with:
         context: ./frontend
-        push: true
-        tags: |
-          ${{ secrets.DOCKER_HUB_USERNAME }}/taski-frontend:latest
-          ${{ secrets.DOCKER_HUB_USERNAME }}/taski-frontend:${{ github.sha }} 
+        push: false
+        load: true
+        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taski-frontend:latest
+
+    - name: Push Frontend
+      run: |
+        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/taski-frontend:latest 
